### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by indrapalijama** [LennonReid/ionic-component-snippets#23]
can you provide me with an user guide on how to implement this component-snippet?
last that i check, there's not a user guide for implementing this

here's my ionic info
<img width="407" alt="Screenshot 2024-07-01 at 4 54 27 PM" src="https://github.com/LennonReid/ionic-component-snippets/assets/33986004/69b41384-8735-494c-b4bb-852c77322895">

**Comment by LennonReid** [comment]
Hey @indrapalijama ,

Sorry for the long delay in getting back to you on this! 🙏 I’ve been meaning to address this, and I’ve finally added a USER GUIDE to the README that should cover how to implement the component snippets. Hopefully, this solves the issue you were facing.

Thanks again for bringing this up, and I’ll keep working to make the project better. Let me know if you run into any more problems or have any other suggestions!

Cheers,
Lennon Reid

**Comment by indrapalijama** [comment]
great, Thanks!
